apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname }}-webhook-configmap
  namespace: {{ .Values.namespace }}
data:
  sidecarconfig.yaml: |
    initContainers:
      - args:
        - /somearg.sh
        image: {{ .Values.keymakerclient.image }}:{{ .Values.keymakerclient.tag }}
        imagePullPolicy: {{ .Values.keymakerclient.pullPolicy }}
        name: init1
        volumeMounts:
        - mountPath: /etc/keytabs
          name: keytabs
      - args:
        - /some-client
        - --service-name=keymaker
        image {{ .Values.keymakerclient.image }}:{{ .Values.keymakerclient.tag }}
        imagePullPolicy: {{ .Values.keymakerclient.pullPolicy }}
        name: init2
        volumeMounts:
        - mountPath: /etc/keytabs
          name: keytabs
    volumes:
      - emptyDir:
          medium: Memory
        name: keytabs
    containers:
      - args:
            - /some-client
            - --runMode=refresh
        name: key-refresher
        image: {{ .Values.keymakerclient.image }}:{{ .Values.keymakerclient.tag }}
        imagePullPolicy: {{ .Values.keymakerclient.pullPolicy }}
        volumeMounts:
        - mountPath: /etc/keytabs
          name: keytabs
  mutationconfig.yaml: |
    mutationConfigs:
      - name: "keymaker"
        annotationNamespace: "keymaker.k8s-integration.sfdc.com"
        annotationTrigger: "inject"
        initContainers: ["init1", "init2"]
        containers: ["key-refresher"]
        volumes: ["keytabs"]
        volumeMounts: ["keytabs"]
        ignoreNamespaces: []
        whitelistNamespaces: []
