---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.webhookPriorityPrefix | default "0001" }}-{{ .Values.appname }}-webhook-cfg
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.namespace }}/{{ .Values.appname }}-certificate
webhooks:
  - admissionReviewVersions: ["v1beta1"] # the webhook supports v1beta1 only
    clientConfig:
      service:
        name: {{ .Values.appname }}
        namespace: {{ .Values.namespace }}
        path: /mutate
    failurePolicy: Fail
    name: {{ .Values.appname }}.sfdc.internal
    namespaceSelector:
      matchExpressions:
        - key: sidecar-injection
          operator: NotIn
          values: ["disabled"]
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
